Repository taejun0/2024_udongchin_front, pull requests merged in 2024-11, with the labels that each got.

#4 Fix: git cache 문제 해결
  src/styles/theme.js
Labels: :hammer_and_wrench: FIx, 🐿️ 태준

#5 fix
  src/components/specific/maps/Navermap.jsx
Labels: :hammer_and_wrench: FIx, 🐿️ 태준

#6 fix: navermapkey
  src/components/specific/maps/MapSelector.jsx
  src/components/specific/maps/Navermap.jsx
Labels: :hammer_and_wrench: FIx, 🐿️ 태준

#7 feat:로그인/회원가입 UI 제작 완료
  src/components/common/buttons/MoveButton.jsx
  src/components/common/buttons/PostButton.jsx
  src/components/common/inputs/TextInput.jsx
  src/components/common/list/CommentList.jsx
  src/components/common/list/CommentListItem.jsx
  src/components/common/list/PostList.jsx
  src/components/common/list/PostListItem.jsx
  src/constant/routeConstants.js
  src/pages/community/FreeBoard.jsx
  src/pages/community/FullBoard.jsx
  src/pages/community/FullStyle.js
  src/pages/community/MainPage.jsx
  src/pages/community/MainStyle.js
  src/pages/community/PostViewPage.jsx
  src/pages/community/PostWritePage.jsx
  src/pages/community/PostWriteStyle.js
  src/pages/community/styled.js
  src/pages/login/JoinPage.jsx
  src/pages/login/JoinStyle.js
  src/pages/login/LoginPage.jsx
  src/pages/login/LoginStyle.js
  src/routes/router.jsx
Labels: :sparkles: Feature, 🐿️ 나연

#9 feat: 마이 우동친 기록 및 서브메뉴 생성
  public/images/ThreeLine.svg
  src/components/common/modals/styled.js
  src/components/layout/header/Header.jsx
  src/components/layout/header/styled.js
  src/components/layout/submenu/Submenu.jsx
  src/components/layout/submenu/styled.js
  src/components/specific/maps/styled.js
  src/components/specific/reportSteps/StepFour.jsx
  src/components/specific/reportSteps/StepOne.jsx
  src/components/specific/reportSteps/StepThree.jsx
  src/components/specific/reportSteps/StepTwo.jsx
  src/constant/routeConstants.js
  src/hooks/useReport.js
  src/pages/homepage/HomePage.jsx
  src/pages/myudchistorypage/MyudchistoryPage.jsx
  src/pages/myudchistorypage/styled.js
  src/pages/udcmanualpage/UdcmanualPage.jsx
  src/pages/udcmanualpage/styled.js
  src/routes/router.jsx
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: :sparkles: Feature, 🐿️ 태준

#12 feature: 내 우동친 기록 페이지 구현
  public/images/folder.svg
  public/images/history_chat.svg
  public/images/history_heart.svg
  public/images/history_location.svg
  public/images/history_nchat.svg
  public/images/history_nheart.svg
  public/images/history_npencil.svg
  public/images/history_ntri.svg
  public/images/history_pencil.svg
  public/images/history_tri.svg
  src/components/layout/header/Header.jsx
  src/components/layout/submenu/Submenu.jsx
  src/components/specific/maps/styled.js
  src/components/specific/myudchistorySteps/MyudchistoryStepOne.jsx
  src/components/specific/myudchistorySteps/MyudchistoryStepTwo.jsx
  src/components/specific/myudchistorySteps/styled.js
  src/components/specific/myudchistorySteps/styled2.js
  src/components/specific/reportSteps/StepThree.jsx
  src/components/specific/reportSteps/StepTwo.jsx
  src/layouts/DefaultLayout.jsx
  src/pages/myudchistorypage/MyudchistoryPage.jsx
  src/pages/myudchistorypage/styled.js
Labels: :sparkles: Feature, 🐿️ 태준

#14 Fix : Font Test 1
  src/components/specific/myudchistorySteps/styled.js
  src/styles/GlobalStyles.js
Labels: :hammer_and_wrench: FIx, :art: Design, 🐿️ 태준

#15 Font Test 2
  src/components/specific/maps/styled.js
  src/pages/homepage/styled.js
Labels: :art: Design, 🐿️ 태준

#17 feature: 긴급 시 지도 디자인 구현
  public/images/marker_urgent.svg
  public/images/sidebar_his.svg
  public/images/sidebar_mymy.svg
  public/images/warning_now.svg
  src/components/common/modals/NaverdetailModal.jsx
  src/components/common/modals/styled.js
  src/components/specific/maps/Navermap.jsx
  src/constant/mockLocations.js
  src/pages/homepage/HomePage.jsx
Labels: :sparkles: Feature, :art: Design, 🐿️ 태준

#19 feature: 현 위치 기능 추가했습니다. (메인페이지 완료)
  public/images/RightLowHome.svg
  public/images/nowlocation_ch.svg
  public/images/sidebar_his.svg
  src/components/specific/maps/Navermap.jsx
  src/components/specific/maps/styled.js
  src/pages/homepage/HomePage.jsx
  src/pages/homepage/styled.js
Labels: :sparkles: Feature, :art: Design, 🐿️ 태준

#22 desgin: 1차 디자인 수정
  src/components/layout/header/Header.jsx
  src/components/layout/submenu/styled.js
  src/components/specific/imageuploader/MultiImageUploader.jsx
  src/components/specific/reportSteps/StepOne.jsx
  src/components/specific/reportSteps/styled.js
  src/pages/homepage/HomePage.jsx
  src/pages/homepage/styled.js
Labels: :hammer_and_wrench: FIx, :art: Design, 🐿️ 태준

#23 design: 사진 및 메인 애니메이션 추가
  public/images/RightLowHome.svg
  public/images/RightLowHome_ch.svg
  public/images/sidebar_his.svg
  src/components/layout/submenu/styled.js
  src/pages/homepage/HomePage.jsx
  src/pages/homepage/styled.js
Labels: :art: Design, 🐿️ 태준

#24 design: 이미지 사이즈 조절 (X)
  src/components/common/modals/QnaMarkerModal.jsx
  src/components/layout/submenu/styled.js
  src/pages/reportpage/ReportPage.jsx
Labels: :art: Design, 🐿️ 태준

#26 design: Pretendard 폰트 적용
  public/fonts/pretendardwoff/Pretendard-Black.woff
  public/fonts/pretendardwoff/Pretendard-Bold.woff
  public/fonts/pretendardwoff/Pretendard-ExtraBold.woff
  public/fonts/pretendardwoff/Pretendard-ExtraLight.woff
  public/fonts/pretendardwoff/Pretendard-Light.woff
  public/fonts/pretendardwoff/Pretendard-Medium.woff
  public/fonts/pretendardwoff/Pretendard-Regular.woff
  public/fonts/pretendardwoff/Pretendard-SemiBold.woff
  public/fonts/pretendardwoff/Pretendard-Thin.woff
  public/fonts/pretendardwoff2/Pretendard-Black.woff2
  public/fonts/pretendardwoff2/Pretendard-Bold.woff2
  public/fonts/pretendardwoff2/Pretendard-ExtraBold.woff2
  public/fonts/pretendardwoff2/Pretendard-ExtraLight.woff2
  public/fonts/pretendardwoff2/Pretendard-Light.woff2
  public/fonts/pretendardwoff2/Pretendard-Medium.woff2
  public/fonts/pretendardwoff2/Pretendard-Regular.woff2
  public/fonts/pretendardwoff2/Pretendard-SemiBold.woff2
  public/fonts/pretendardwoff2/Pretendard-Thin.woff2
  src/components/common/modals/styled.js
  src/components/layout/header/styled.js
  src/components/layout/submenu/styled.js
  src/components/specific/maps/styled.js
  src/components/specific/myudchistorySteps/styled.js
  src/components/specific/myudchistorySteps/styled2.js
  src/components/specific/reportSteps/StepOne.jsx
  src/components/specific/reportSteps/StepTwo.jsx
  src/components/specific/reportSteps/styled.js
  src/pages/homepage/styled.js
  src/pages/reportpage/styled.js
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: :art: Design, 🐿️ 태준

#27 design: 전체 폰트 수정
  public/fonts/nanum-square-round/NanumSquareRoundB.ttf
  public/fonts/nanum-square-round/NanumSquareRoundEB.ttf
  public/fonts/nanum-square-round/NanumSquareRoundL.ttf
  public/fonts/nanum-square-round/NanumSquareRoundOTFB.otf
  public/fonts/nanum-square-round/NanumSquareRoundOTFEB.otf
  public/fonts/nanum-square-round/NanumSquareRoundOTFL.otf
  public/fonts/nanum-square-round/NanumSquareRoundOTFR.otf
  public/fonts/nanum-square-round/NanumSquareRoundR.ttf
  src/components/common/modals/styled.js
  src/components/layout/header/styled.js
  src/components/layout/submenu/styled.js
  src/components/specific/maps/styled.js
  src/components/specific/myudchistorySteps/styled.js
  src/components/specific/myudchistorySteps/styled2.js
  src/components/specific/reportSteps/styled.js
  src/pages/homepage/styled.js
  src/pages/reportpage/ReportPage.jsx
  src/pages/reportpage/styled.js
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: :art: Design, 🐿️ 태준

#31 design:폰트수정 및 디자인 점검
  src/components/layout/submenu/Submenu.jsx
  src/components/layout/submenu/styled.js
  src/pages/community/Boardstyled.js
  src/pages/community/MainStyle.js
  src/pages/community/PostViewPage.jsx
  src/pages/community/PostWritePage.jsx
  src/pages/community/styled.js
  src/pages/login/JoinPage.jsx
  src/pages/login/LoginPage.jsx
  src/pages/login/styled.js
Labels: :art: Design, 🐿️ 나연

#37 feature: 메인페이지 버튼 재구성 및 토스트바 설정
  public/images/adding_chat.svg
  public/images/adding_dots.svg
  public/images/adding_pencil.svg
  src/components/common/Toasts/Toast1.jsx
  src/components/common/Toasts/Toast2.jsx
  src/components/common/modals/QnaMarkerModal.jsx
  src/components/common/modals/styled.js
  src/components/specific/maps/Navermap.jsx
  src/components/specific/maps/styled.js
  src/constant/mockLocations.js
  src/pages/homepage/HomePage.jsx
  src/pages/homepage/styled.js
Labels: :sparkles: Feature, :art: Design, 🐿️ 태준

#39 feature: 생태지도 디테일 모달, 미로그인시 로그인 유도 모달
  public/images/mapmodal_bottom.svg
  public/images/mapmodal_next.svg
  public/images/marker_real.svg
  public/images/marker_sengtae.svg
  src/components/common/modals/MapModal.jsx
  src/components/common/modals/WarningLoginModal.jsx
  src/components/common/modals/styled.js
  src/components/specific/maps/Navermap.jsx
  src/constant/mockLocations.js
  src/pages/homepage/HomePage.jsx
  src/styles/theme.js
Labels: :sparkles: Feature, :art: Design, 🐿️ 태준

#43 feature: 커뮤니티용 지도 구현
  public/images/Sengtae/squrrel.png
  public/images/adding_dots.svg
  src/components/common/modals/MapModal.jsx
  src/components/specific/maps/CommunityMap.jsx
  src/components/specific/maps/Navermap.jsx
  src/constant/mockLocations.js
  src/pages/homepage/HomePage.jsx
  src/utils/coordinateUtils.js
Labels: :sparkles: Feature, :art: Design, 🐿️ 태준

#50 api: 메인페이지 API작업을 한다.
  src/components/common/modals/NaverdetailModal.jsx
  src/components/common/modals/QnaMarkerModal.jsx
  src/components/specific/cropImage.jsx
  src/components/specific/imageuploader/ImageUploader.jsx
  src/components/specific/imageuploader/MultiImageUploader.jsx
  src/components/specific/maps/Kakaomap.jsx
  src/components/specific/maps/Navermap.jsx
  src/components/specific/myudchistorySteps/MyudchistoryStepOne.jsx
  src/components/specific/myudchistorySteps/MyudchistoryStepTwo.jsx
  src/components/specific/myudchistorySteps/styled2.js
  src/components/specific/reportSteps/StepFour.jsx
  src/components/specific/reportSteps/StepOne.jsx
  src/components/specific/reportSteps/StepThree.jsx
  src/components/specific/reportSteps/StepTwo.jsx
  src/constant/mockLocations.js
  src/contexts/AuthContext.jsx
  src/hooks/useImageLoad.js
  src/hooks/useQnaMarkerPost.js
  src/hooks/useReport.js
  src/hooks/usemyComment.js
  src/hooks/usemyLike.js
  src/hooks/usemyPost.js
  src/pages/homepage/HomePage.jsx
  src/pages/myudchistorypage/MyudchistoryPage.jsx
  src/services/instance.js
  src/services/locationImageService.js
  src/services/login.js
  src/services/mycommentService.js
  src/services/mylikeService.js
  src/services/mypostService.js
  src/services/qna.js
  src/services/reportService.js
  src/services/signUp.js
  src/utils/blobUtils.js
  src/utils/coordinateUtils.js
Labels: :books: API, 🐿️ 태준

#53 Fix/#52 width 제한하기
  public/images/adding_exclamation.svg
  src/pages/homepage/HomePage.jsx
  src/services/qna.js
  src/styles/GlobalStyles.js
Labels: :hammer_and_wrench: FIx, 🐿️ 태준
